pipeline{
    agent { label 'dev' }

    stages {
        stage('Fetch code from github'){
            steps {
                git url : 'https://github.com/mohsinali421/Jenkins.git', branch: 'master'
            }
        }

        stage('Build and Test'){
            steps {
                echo "Build Started"
                sh 'docker build -t my-app ./DockerWithJenkins/.'
            }
        }

        stage('login and Push image'){
            echo 'Login done'
        }

        stage('Deploy'){
            steps {
                echo 'Deployment started'
                sh 'docker-compose down && docker-compose up -d'
            }
        }

    }
}